### ISSUE TITLE
can you give some suggestion about how to learn 3d reconstruction for a recruit like me?

### ISSUE THREAD

**Issue by shoutOutYangJie** [YadiraF/DECA#11]
hi, I am a new beginner at this direction. before now, I work at video segmentation task. Now I want to change my direction, but I find some diffculties, since this direction, 3d reconstruction is too strange for me. so I want to ask for your help. Can you share your experiences about how you started to learn this direction. Thank you.

**Comment by TimoBolkart** [comment]
I would recommend getting familiar with statistical 3D models first. For reading, I would recommend that [survey article](https://arxiv.org/abs/1909.01815) as a good starting point. For getting hands on statistical face models, you find several different demos linked [here](https://flame.is.tue.mpg.de/download.php) that demonstrate different applications of a 3D face model. I would recommend starting with some Image landmark fitting (as e.g. provided [here](https://github.com/TimoBolkart/TF_FLAME)) to get familiar with 3D reconstruction. Once you have some sense for the optimization-based 3D face reconstruction, understanding whats going on in regression-based methods like DECA should be easier.

**Comment by shoutOutYangJie** [comment]
@TimoBolkart 
Thank you!!!

**Comment by prokaryote-hgy** [comment]
@TimoBolkart Hello, the second link you shared is invalid. Do you have any similar demo repositories?

**Comment by TimoBolkart** [comment]
True, we moved the FLAME website on a different server, so the ending .php was missing. I edited the link and it should work again (you must be logged in to the FLAME website to show the download section). Another list of FLAME-based projects you can find [here](https://github.com/TimoBolkart/FLAME-Universe).

**Comment by prokaryote-hgy** [comment]
@TimoBolkart Thanks a lot!
