### ISSUE TITLE
Access estimated transformation of mesh

### ISSUE THREAD

**Issue by mjvanderboon** [YadiraF/DECA#110]
Hi, thanks for the great work and repository.

I am looking to access the estimated homogeneous transform that aligns the mesh from an initial frame to a frame that is aligned with the camera position of an input image. Or conversely the homogeneous transform that transform the camera pose to align the mesh with the image.

I suspect that the rotational information I need is available as an angle axis representation in the first pose entry in the code_dict: `code_dict['pose'][..., 0:3]`, could you confirm this is correct? I also suspect the translation vector I desire is available as `code_dict['cam']`, but I am unsure how to transform this `[scale, t_x, t_y]` vector into a translation vector in R3. 

Could you provide any hints or pseudocode on how to generate a homogeneous transformation matrix from the available pose estimation?

**Comment by FeiiYin** [comment]
Can the `tform` in dataset works?

**Comment by FeiiYin** [comment]
Can the `tform` in dataset work?

**Comment by mjvanderboon** [comment]
I looked at the code in `/decalib/datasets/datasets.py` and I would be able to write a similar functionality to extract the estimated transformation for a general input image using a face detector. However, as far as I understand `code_dict['pose']` should also encode the pose of the face together with `code_dict['cam']`. Do you know if this is correct? Or do these values encode other parameters?

**Comment by mjvanderboon** [comment]
A bit more detail is available in the issue linked above. It explains how to use code_dict['pose'] and code_dict['cam'] to estimate full homogeneous transformation matrices.
