### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by MollyHoo** [YadiraF/DECA#126]
RuntimeError: Error building extension 'standard_rasterize_cuda': [1/3] :/usr/local/cuda-11.2/bin/nvcc -DTORCH_EXTENSION_NAME=standard_rasterize_cuda -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -ccbin=$(which gcc-7) -c /home/seemmo/DECA/decalib/utils/rasterizer/standard_rasterize_cuda_kernel.cu -o standard_rasterize_cuda_kernel.cuda.o
FAILED: standard_rasterize_cuda_kernel.cuda.o
:/usr/local/cuda-11.2/bin/nvcc -DTORCH_EXTENSION_NAME=standard_rasterize_cuda -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -ccbin=$(which gcc-7) -c /home/seemmo/DECA/decalib/utils/rasterizer/standard_rasterize_cuda_kernel.cu -o standard_rasterize_cuda_kernel.cuda.o
/bin/sh: 1: :/usr/local/cuda-11.2/bin/nvcc: not found
[2/3] c++ -MMD -MF standard_rasterize_cuda.o.d -DTORCH_EXTENSION_NAME=standard_rasterize_cuda -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/seemmo/DECA/decalib/utils/rasterizer/standard_rasterize_cuda.cpp -o standard_rasterize_cuda.o
FAILED: standard_rasterize_cuda.o
c++ -MMD -MF standard_rasterize_cuda.o.d -DTORCH_EXTENSION_NAME=standard_rasterize_cuda -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/TH -isystem /home/seemmo/.local/lib/python3.7/site-packages/torch/include/THC -isystem :/usr/local/cuda-11.2/include -isystem /usr/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/seemmo/DECA/decalib/utils/rasterizer/standard_rasterize_cuda.cpp -o standard_rasterize_cuda.o
In file included from /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/Device.h:3:0,
                 from /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                 from /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/extension.h:6,
                 from /home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:6,
                 from /home/seemmo/DECA/decalib/utils/rasterizer/standard_rasterize_cuda.cpp:1:
/home/seemmo/.local/lib/python3.7/site-packages/torch/include/torch/csrc/python_headers.h:10:20: fatal error: Python.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.

could you help me. i have tried for cuda10.1+cudnn7.6.5+torch1.6.0+torchvision0.7.0+ubuntu16.04  
always this error.

**Comment by Gregorein** [comment]
@MollyHoo

**Comment by JonathanLehner** [comment]
did you find any?

**Comment by YunliYin** [comment]
Did you find any solutions to this error? I met the same error.

**Comment by chenerg** [comment]
Just use --rasterizer_type=pytorch3d to bypass the self-implemented rasterlization version.

**Comment by zhuzhiwei99** [comment]
# Solution1:  
 use `--rasterizer_type=pytorch3d` to bypass the self-implemented rasterlization version which will generate *standard_rasterize_cuda.o* at the beginning of the program.
# Solution2: 
change the gcc version to gcc-7, you can use following command:
```
sudo apt install gcc-7
sudo unlink /usr/bin/gcc 
sudo ln -s /usr/bin/x86_64-linux-gnu-gcc-7 /usr/bin/gcc
```
You also can look up this blog for the details: [【ubuntu】gcc/g++傻傻分不清？如何实现ubuntu多版本gcc/g++切换](https://blog.csdn.net/weixin_43693967/article/details/123719406?csdn_share_tail=%7B%22type%22%3A%22blog%22%2C%22rType%22%3A%22article%22%2C%22rId%22%3A%22123719406%22%2C%22source%22%3A%22weixin_43693967%22%7D)

**Comment by chuanheliu** [comment]
The same problem

Ubuntu20, gcc9,g++9 Faild. 

Then I update the gcc and g++ like this:
```

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update

sudo apt-get install gcc-7 g++-7

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7
sudo update-alternatives --config gcc

gcc --version
```

It works
