### ISSUE TITLE
How to get the face region?

### ISSUE THREAD

**Issue by puppet101** [YadiraF/DECA#13]
@ TimoBolkart, thanks for your great work!
I notice that in figure 2 of your paper, the resulting image only contains the rendered face region, but in your reconstruction demo, the rendered texture shows the full head result. So could you please give some instructions on how to get the face and eye region only, not containing other parts?
![reliao_img_1608545228215](https://user-images.githubusercontent.com/9941762/102765363-7c64f780-43b7-11eb-865f-088084691f09.png)

**Comment by TimoBolkart** [comment]
If you want subsets of vertices of FLAME, you can use the FLAME Vertex Masks from the FLAME website. These give the vertex indices for different masks. Does that help?

**Comment by maty-bohacek** [comment]
Hi @TimoBolkart, would you please point me to these "FLAME Vertex Masks"? I can't find them on the FLAME website. Many thanks in advance!
