### ISSUE TITLE
Question about how to choosing 4 images per identity?

### ISSUE THREAD

**Issue by wearegolden** [YadiraF/DECA#130]
I have a question regarding the training process.

In the paper, it says that you chose 950k images from the vggface2 dataset.
After that, it says that for the coarse model, you only used 4 images per subject.
But as far as I know, the vggface2 dataset has around 9k subjects (around 350images each).
Then this would lead to 9k * 4 = 36k images, which is way smaller than 950k. 
Am I misunderstanding something? Or do you use 950k in the pretraining step? Or is it that there are duplicated subjects of 4 images?

I welcome any response!
Thank you

**Comment by TimoBolkart** [comment]
This 4 images per subject refers to a minibatch. Each batch of 32 images contains images of 8 distinct subjects, with 4 images per subject. Does this answer your question?

**Comment by wearegolden** [comment]
I understood that part, but that amounts to 9k * 4 = 36k images (4 images per subject, 9k subjects in VGGFace2). In the paper it says they used 950k images from the vggface2 dataset. The numbers don't add up!

**Comment by TimoBolkart** [comment]
It seems there is a misunderstanding. Overall, there are much more than 4 images used per subject. This statement only refers to the composition of one minibatch, which contains multiple (i.e., 4) images of one subject. The next minibatch can contain another 4 images of that subject or of any other subject.

**Comment by wearegolden** [comment]
That makes much more sense. Thank you so much for your kind reply.
