### ISSUE TITLE
How to translation the rendered images?

### ISSUE THREAD

**Issue by yuhaoooo** [YadiraF/DECA#16]
Thanks for this exciting work.
I have a question about how to adjust the position of rendered images, as illustrated in the below image.
![image](https://user-images.githubusercontent.com/24415219/103259714-7da8ac80-49d5-11eb-8cd1-68ea06c2f8ce.png)

The left image is the rendered image, which is perfect. And I want to move down this image so that the neck part will be deleted. The key point here is that in the processed image, the forehead part should be shown, just like the right image.

But you can see the pose between the right image and the left image is much more different.

ps. the right image is generated by changing positions of `transformed_vertices` in `SRenderY.forward()`.
```
transformed_vertices[:, :, :2] = transformed_vertices[:, :, :2] * self.image_size / 2 + self.image_size / 2
transform = torch.tensor(t_form, dtype=torch.float32).to(images.device).unsqueeze(0)
transform[:, :2, 2] = - transform[:, :2, 2]
transformed_vertices= torch.einsum('bij,bkj->bki', transform, transformed_vertices)
transformed_vertices[:, :, :2] = transformed_vertices[:, :, :2] / self.image_size * 2. - 1.
```
And `t_form` is
```
[
   [1, 0, 0],
   [0, 1, 20],
   [0, 0, 1]
]
```

Can you give me any advice to implement this work?

**Comment by Dratlan** [comment]
Hi, can you share you solutions for implement this work @csyuhao
