### ISSUE TITLE
resnet50_ft_weight.pkl missing

### ISSUE THREAD

**Issue by Javisda** [YadiraF/DECA#183]
It seems to need this file resnet50_ft_weight.pkl when initializing the Trainer but I can`t find this anywhere. Any clue?

**Comment by Javisda** [comment]
Sorry, my bad. The link is in the training readme :D

**Comment by acmlau** [comment]
@Javisda Hi! I am trying to reproduce this work. Can I ask you if you used the datasets DECA used (i.e. [VGGFace2](https://arxiv.org/pdf/1710.08092.pdf), [BUPT-Balancedface](http://www.whdeng.cn/RFW/Trainingdataste.html) and [VoxCeleb2](https://www.robots.ox.ac.uk/~vgg/data/voxceleb/vox2.html)?

**Comment by Javisda** [comment]
@acmlau Hi! I have not been able to use the datasets. Instead, I'm testing with my own images. I still don't know how all this fit together so I'm still struggling.
