### ISSUE TITLE
 Unknown CUDA

### ISSUE THREAD

**Issue by gkadntmd** [YadiraF/DECA#190]
GPU:RTX4090
env cuda toolkit:10.2
torch version:1.6.0

error:ValueError: Unknown CUDA arch (8.9) or GPU not supported

Could you help me with the issue? Thank you!

**Comment by DanielSHKao** [comment]
Same issue here. @gkadntmd , may I ask whether you solve the problem? How do you solve it?

**Comment by KeyForce** [comment]
same issue
