### ISSUE TITLE
wrong result

### ISSUE THREAD

**Issue by gkadntmd** [YadiraF/DECA#191]
![id08456-SEvpX9LhEP4-000957_inputs_inputs_vis](https://github.com/yfeng95/DECA/assets/69135376/7edc95e7-f7ae-41e2-8ca7-6eaa0a0a08ea)

I ran the demo, but it gives me a result that can't catch the shape like this. Is it because of some problem?

thank you for your help!

**Comment by MilesTheProwler** [comment]
Did you solve it ? I have that problem too.

**Comment by sw1014** [comment]
> Did you solve it ? I have that problem too.

Hi, I encountered the same problem. Have you managed to resolve it? Could you please share some advice?
