### ISSUE TITLE
Drawing facial keypoints on original image

### ISSUE THREAD

**Issue by vladimirmujagic** [YadiraF/DECA#20]
Hello,

I am trying to remap tile valid coordinates to original image valid coordinates.

To be more precise your demo script creates a torch grid out of multiple tiles that detector produces `2dlandmarks, 3dlandmarks, ...` i want to be able to pass input image e.g `1280x720` use your preprocessing to create input tile `224x224` detect landmarks and then draw them on original image, for this i need to apply inverse transformation on keypoints based on preprocessing transformations.

Here is some sample code i am testing
```
# Test 1000x1000 input image
image = cv2.imread('/path/to/test/img.jpg')

testdata = datasets.TestData('/path/to/test/img.jpg', iscrop=True, face_detector='fan')
name = testdata[0]['imagename']
images = testdata[0]['image'].to('cuda')[None, ...]
# Modified to return bbox as well
bbox = testdata[0]['bbox']

deca = DECA(config=deca_cfg, device='cuda')
codedict = deca.encode(images)
opdict, visdict = deca.decode(codedict)  # tensor


start_point = (bbox[0], bbox[1])
end_point = (bbox[2], bbox[3])
cv2.rectangle(image, start_point, end_point, (255, 0, 0), 2)

color = (255, 111, 111)
for landmark in opdict['landmarks2d'][0]:
    # Valid coordinates on croped face tile
    xr = landmark[0].item()
    yr = landmark[1].item()

     # Try to produce original image valid coordinates
    xr = xr * 224/1000 + bbox[0]
    yr = yr * 224/1000 + bbox[1]
    xr = int(xr)
    yr = int(yr)

    cv2.circle(image, (xr, yr), 1, color, 1, cv2.LINE_AA)
```

So what would be the transformation since
```
original_valid_x = tile_valid_x * tile_width / original_width + tile_origin_x
original_valid_y = tile_valid_y * tile_height / original_height + tile_origin_y
```
are not producing expected results

**Comment by KeyKy** [comment]
@YadiraF Could you offer an interface to get the 3d obj pose in original image, not the cropping image patch?

**Comment by YadiraF** [comment]
Hi drawing the results in original image now is available, please set --render_orig True, thanks!

**Comment by BostonLobster** [comment]
@KeyKy Hi, have you find the way to get the 3D obj pose in original image rather than the cropping region?
