### ISSUE TITLE
About the test results of PRNet on NoW

### ISSUE THREAD

**Issue by ChangY-7** [YadiraF/DECA#23]
hello, thanks for your great job! I am a little confused about the test results on NoW dataset. 

Now that all the scans in NoW are neutral ones and the methods need to exclude expressions before testing. How do you test the PRNet? Do you just test the neural images, or just keep the results with expressions? It seems PRNet cannot exclude expressions.

Looking forward to your reply, thank you.

**Comment by TimoBolkart** [comment]
For methods that do not disentangle identity shape and expression variations (e.g. for PRNet), we directly use the 3D reconstruction to compute the error. 

Note that this, out of the four NoW challenges "neutral, expression, occlusion, and selfie" potentially only influences the error for expression and selfie, as neutral and occlusion are in neutral expression. As shown in Figures 8, 9, 10, and 11 of the [RingNet paper ](https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/509/paper_camera_ready.pdf) PRNet consistently has a higher error, also for neutral expression images.
