### ISSUE TITLE
FLAME_albedo_from_BFM

### ISSUE THREAD

**Issue by ZekuiQin** [YadiraF/DECA#25]
Could you please share the FLAME_albedo_from_BFM.npz?
It is difficult for me to get that.
Thanks!

**Comment by TimoBolkart** [comment]
Please follow that instructions [BFM_to_FLAME](https://github.com/TimoBolkart/BFM_to_FLAME) to get the FLAME_albedo_from _BFM.npz
It is not possible for us to share derived data from the Basel Face model, therefore we cannot directly share this file.
Thanks for your understanding

**Comment by muteeb360** [comment]
i got that file from hugging face. this is the link
[https://huggingface.co/camenduru/TalkingHead/blob/main/FLAME_albedo_from_BFM.npz](url)
