### ISSUE TITLE
Not running tests

### ISSUE THREAD

**Issue by danperazzo** [YadiraF/DECA#43]
Hello everyone, thanks for releasing your code! I have been trying to run it and my setup is the same as described in the paper (pytorch, torchvision, and the latest pytorch3d) However, I encounter this error message: `fc.weight  not available in reconstructed resnet
fc.bias  not available in reconstructed resnet
fc.weight  not available in reconstructed resnet
fc.bias  not available in reconstructed resnet
`

And at the end this error: `File "/home/daniel/Desktop/DECA/decalib/utils/util.py", line 545, in plot_kpts
    image = cv2.circle(image,(st[0], st[1]), 1, c, 2)  
cv2.error: OpenCV(4.5.2) : -1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
`

What can I do?

**Comment by danperazzo** [comment]
Resolved it!

**Comment by seungwonpark** [comment]
I've got same errors and resolved it by casting the landmark arrays into int.

tensor_vis_landmarks at decalib/utils/util.py
```
    if gt_landmarks is not None:
        gt_landmarks_np = gt_landmarks.detach().cpu().numpy()
        gt_landmarks_np = gt_landmarks_np.astype(int)
    
    predicted_landmarks = predicted_landmarks.astype(int)
```
