### ISSUE TITLE
Parameter difference from Flame original model

### ISSUE THREAD

**Issue by avartation** [YadiraF/DECA#46]
I want to use the output of DECA in Blender addon from the Flame website.
So DECA gives

- 100 shape parameters
- 50 expression parameters

But the original Flame model (used in Blender addon) has 

- 300 shape parameters
- 100 expression parameters

Is there a way to get original Flame parameters from DECA parameters ?
Thanks !

**Comment by TimoBolkart** [comment]
The DECA output is a real subset of the full FLAME 2020 model. You can just use the DECA output as the first 100 identity shape and 50 expression shape parameters. The rest of the parameters you can set to zero. Does that answer your question?

**Comment by avartation** [comment]
Thanks a lot @TimoBolkart, now I got it !

P.S. 
I have another similar question related to the _Flame Blender Add-on_.
I opened another [issue](https://github.com/TimoBolkart/FLAME-Blender-Add-on/issues/1) in _FLAME Blender Add-on_'s repository, will be happy to get an answer for that as well.

Thanks again for this awesome work !

**Comment by Elsaam2y** [comment]
Hi,

I found that the values of the expressions are too low compared to the range of the values in Blender. Is that normal? After mapping the values to the model in Blender I don't get the exact reconstruction.
Regarding the pose values. Should I assign them also to the first 6 poses of the 18 in Blender?
Compared to Smplify-X, the model doesn't extract the Jaw, left and right eyes. How can then be set correctly in Blender? Should simplify-x be abetter option in this case?

Thanks in advance

**Comment by qiliux** [comment]
> Hi,
> 
> Regarding the jaw value (Set jaw), I have assigned it based on the predicted 2d landmarks since without the jaw, the output won't look complete `bpy.data.window_managers["WinMan"].flame_tool.flame_jaw = <value>`. However, I can't keyframe the value for the jaw since it is not a shape key (I need to keyframe since I want to export an fbx for a video, not a single frame). Any ideas?
> 
> Thanks in advance

I am working on this too. DId you find a solution?

**Comment by xiaoyang333** [comment]
> DECA 输出是完整 FLAME 2020 模型的真实子集。您可以只使用 DECA 输出作为前 100 个身份形状和 50 个表达式形状参数。其余参数可以设置为零。这是否回答你的问题？

用参数得到的脸部网格完全不准？有和我一样看法的人吗？为什么会这样
