### ISSUE TITLE
Can DECA handle the eye gaze?

### ISSUE THREAD

**Issue by sukun1045** [YadiraF/DECA#48]
Hi, great paper and nice repo that is easy to use. I have a question related to the eye gaze direction. In the FLAME model, the pose params include the eyeball. However, in the DECA paper, it seems like only taking care of head pose and jaw pose. I am wondering whether the eye gaze is a hard problem. Besides, is there any existing tool that can handle the eye gaze in the reconstruction? Thank you.

**Comment by TimoBolkart** [comment]
Hi, DECA does not reconstruct the eyeball pose parameters from the image, so gaze is not considered. Given a reliable gaze annotation method for the training images, this could be integrated into the DECA training though.
