### ISSUE TITLE
deca_model.tar is probably broken.

### ISSUE THREAD

**Issue by cedro3** [YadiraF/DECA#5]
deca_model.tar is probably broken and cannot be unzipped.

**Comment by TimoBolkart** [comment]
Please just copy the deca_model.tar as mentioned in the Readme. You don't need unzip it

**Comment by cedro3** [comment]
I understood. Thanks.

> 2020/12/14 6:33、TimoBolkart <notifications@github.com>のメール:
> 
> Please just copy the deca_model.tar as mentioned in the Readme. You don't need unzip it
