### ISSUE TITLE
DECA-HR availibility

### ISSUE THREAD

**Issue by pstorozenko** [YadiraF/DECA#63]
Hello,
I find this model very interesting and I'd like to experiment more with it.
In the research paper you write "To further research on this topic, we also release a model trained using high-resolution images only (i.e. DECA-HR).".
However I wasn't able to find this model anywhere.
Have the plans been abandoned?

Best

**Comment by DefTruth** [comment]
same question ~

**Comment by HavenFeng** [comment]
Hi, since this repo has been heavily refactored after the submission, the previously trained HR model is not compatible right now. We plan to retrain a new HR model based on the current repo and release it soon, stay tuned:)
