### ISSUE TITLE
compatibility w/ pytorch3d

### ISSUE THREAD

**Issue by jnwnlee** [YadiraF/DECA#78]
I'm using pytorch3d(==0.5.0) for rasterizer_type as the standard one occurs compile error.
However, it seems the latest commit doesn't work with pytorch3d properly..

![image](https://user-images.githubusercontent.com/79582852/138637480-69b97d6e-2834-4d9e-8fd4-4b89d07447c4.png)
err message:
Traceback (most recent call last):
  File "demos/demo_reconstruct.py", line 126, in <module>
    main(parser.parse_args())
  File "demos/demo_reconstruct.py", line 52, in main
    opdict, visdict = deca.decode(codedict) #tensor
  File "/media/user/data/Exp/DECA/decalib/deca.py", line 229, in decode
    shape_images, _, grid, alpha_images = self.render.render_shape(verts, trans_verts, h=h, w=w, images=background, return_grid=True)
  File "/media/user/data/Exp/DECA/decalib/utils/renderer.py", line 360, in render_shape
    rendering = self.rasterizer(transformed_vertices, self.faces.expand(batch_size, -1, -1), attributes, h, w)
  File "/home/user/anaconda3/envs/decan/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes from 3 to 4 positional arguments but 6 were given

cudatoolkit==10.1
numpy==1.20.3
scipy==1.7.1
chumpy==0.70
scikit-image==0.18.3
opencv-python==4.5.4.58
PyYAML==5.1.1         
torch==1.6.0   # for compatible with pytorch3d
torchvision==0.7.0
face-alignment==1.3.5
yacs==0.1.8
ninja==1.10.2.2
pytorch3d==0.5.0 #pytorch3d-nightly
kornia==0.6.1

(In addition, it seems kornia==0.6.1 officially supports torch>=1.8.1 which crushes with pytorch3d's requirement ==1.6.0)

**Comment by YadiraF** [comment]
Could you send me the image example? So I can also try and debug, because it works well in my side. 
And which pytorch3d are you using? it should work with pytorch3d 0.4.0 or later, where Non Square Image Rasterization for Meshes is supported.

**Comment by jnwnlee** [comment]
I used one of your non-square example images, but found out that I was using pytorch3d 0.3.0
trying to install >=0.4.0, but confronting conflicts in both python 3.6 & 3.7
I'm currently searching for solutions. Sorry for the confusion.

![image](https://user-images.githubusercontent.com/79582852/139767175-15a24d0c-00c1-46df-9cc9-fa20ff931dfa.png)
(installing fvcore didn't resolve my case)

**Comment by jnwnlee** [comment]
I solved my issue by the following command
(reinstalling fvcore and iopath)
``` conda install -c fvcore -c iopath -c conda-forge fvcore iopath
Refer to this link for anyone who's struggling with python version or glibc version issue..
https://github.com/facebookresearch/pytorch3d/issues/655

I'll close the case as it works just fine after installing pytorch3d 0.6.0
Thank you for your support!
