### ISSUE TITLE
DECA model tar file is corrupted?

### ISSUE THREAD

**Issue by RohithPillai** [YadiraF/DECA#8]
The DECA model tar file downloaded from here (https://drive.google.com/file/d/1rp8kdyLPvErw2dTmqtjISRVvQLj6Yzje) cannot be unpacked. Trying to unpack with tar on terminal gives:

`tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors`

Any idea why this is? How do I unpack this file?

**Comment by Michaelwhite34** [comment]
You don't need to unzip it...Just copy it to that place.
