### ISSUE TITLE
Which model is used for 3D reconstruction?

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [YadiraF/DECA#87]
It feels a bit like smplx, can you map the result to the key points of smplx's face?

**Comment by TimoBolkart** [comment]
Yes, FLAME and SMPL-X are in full correspondence, for details, please see [this repo](https://github.com/vchoutas/smplx). 
Our [PIXIE](https://github.com/YadiraF/PIXIE) expressive body (i.e., fullbody with articulated hands and expressive faces) regressor also maps DECA's detail displacements to SMPL-X to get an expressive body with detailed faces. 

Does this answer your question?
