### ISSUE TITLE
FLAME model 404

### ISSUE THREAD

**Issue by 523997931** [YadiraF/DECA#89]
hi I want to download the pretrained model,but the FLAME model show 404

**Comment by xiaochunxin** [comment]
i meet the same problem too!

**Comment by MichaelJBlack** [comment]
Sorry, the path was wrong and it should work now.  Please try again.

**Comment by AdamMayor2018** [comment]
It still shows 404 now, chould u please check again?

**Comment by icedpanda** [comment]
Hi @MichaelJBlack, the link is still invalid; could you please double-check it again? Cheers

**Comment by YadiraF** [comment]
@icedpanda  I just updated the path, could you try again? thanks!

**Comment by icedpanda** [comment]
Hi @YadiraF, thanks for the quick reply, and now I can access the site. However, I am facing the same issue as #95 described; I have checked my junk folder, but nothing has arrived. Any workaround? Thanks

**Comment by icedpanda** [comment]
Never mind, I got the activation link this morning. 👍
